version: "3"

services:
    agwallet-api:
        build:
            context: .
        depends_on:
            - agwallet-postgres
        environment:
            DATABASE_URL: postgres://agwallet:password@postgres:5437/agwalletdb
            NODE_ENV: development
            PORT: 8000
        ports:
            ["8000:8000"]
        restart: always
        networks:
            [awesome]

    agwallet-postgres:
        hostname: agwallet-postgres
        container_name: agwallet-postgres
        image: postgres:9.6.5-alpine
        ports:
            ['5437:5432']
        volumes:
            - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
        restart: always
        environment:
            POSTGRES_USER: agwallet
            POSTGRES_PASSWORD: password
            POSTGRES_DB: agwalletdb
        networks:
            [awesome]

    agwallet-pgadmin:
            container_name: agwallet-pgadmin
            image: dpage/pgadmin4:4.18
            restart: always
            environment:
                PGADMIN_DEFAULT_EMAIL: admin@admin.com
                PGADMIN_DEFAULT_PASSWORD: secret
                PGADMIN_LISTEN_PORT: 80
            ports:
                ["8080:80"]
            volumes:
                - pgadmin-data:/var/lib/pgadmin
            depends_on:
                - agwallet-postgres
            networks:
                [awesome]
            
volumes:
    pgadmin-data:

networks:
    awesome:
        driver: bridge