version: "3"

services:
    sample-api:
        build:
            context: .
        depends_on:
            - sample-postgres
        environment:
            DATABASE_URL: postgres://sampleUser:password@postgres:5437/sampledb
            NODE_ENV: development
            PORT: 8000
        ports:
            ["8000:8000"]
        restart: always
        networks:
            [awesome]

    sample-postgres:
        hostname: sample-postgres
        container_name: sample-postgres
        image: postgres:9.6.5-alpine
        ports:
            ['5437:5432']
        volumes:
            - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
        restart: always
        environment:
            POSTGRES_USER: sampleUser
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sampledb
        networks:
            [awesome]
            
    sample-postgres-test:
        hostname: sample-postgres-test
        container_name: sample-postgres-test
        image: postgres:9.6.5-alpine
        ports:
            ['5438:5432']
        volumes:
            - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
        restart: always
        environment:
            POSTGRES_USER: sampleUser
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sampledb
        networks:
            [awesome]

    sample-pgadmin:
            container_name: sample-pgadmin
            image: dpage/pgadmin4:4.18
            restart: always
            environment:
                PGADMIN_DEFAULT_EMAIL: admin@admin.com
                PGADMIN_DEFAULT_PASSWORD: secret
                PGADMIN_LISTEN_PORT: 80
            ports:
                ["8080:80"]
            volumes:
                - pgadmin-data:/var/lib/pgadmin
            depends_on:
                - sample-postgres
            networks:
                [awesome]
            
volumes:
    pgadmin-data:

networks:
    awesome:
        driver: bridge